### ISSUE TITLE
Ender IO Bug

### ISSUE THREAD

**Issue by TheRealShohi** [JagSwag2014/NBSolder-Mods#7]
I've had a bug with ender io meaning that I couldn't craft a sag mill or a double layer capacitor i would form the recipe in the crafting table and the item would appear but I can't take it out and if I do it goes straight back in I gave the items for the sag mill to a mod in return for it but the bug is still there and I still can't craft the capacitor it seems that if crafting an item with an ender io item in the recipe it won't work but I don't know that for sure thank you for reading.

**Comment by JagSwag2014** [comment]
Fixed in latest update.
